In [39]:
import numpy as num

In [2]:
a=num.array([1,2,4,2])    # sabit bir tip tutar

In [3]:
type(a) 

numpy.ndarray

In [5]:
num.array([3.12,43,2,56])  ## hepsini float yaptı sabit tip

array([ 3.12, 43.  ,  2.  , 56.  ])

In [6]:
num.array([3.12,43,2,56], dtype="int" )

array([ 3, 43,  2, 56])

In [7]:
### sıfırdan array oluşturma

In [8]:
num.zeros((5))

array([0., 0., 0., 0., 0.])

In [5]:
num.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
num.full((3,5),8)  ## 3 e 5 lik 8 lerden oluşan array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [11]:
num.arange(0,30,4)  # 0 dan 30 a kadar 4 er 4 er 

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [9]:
a =num.linspace(1,5,6, dtype= "int")  ## 1 ile 5 arasında 6  sayı oluştur
a

array([1, 1, 2, 3, 4, 5])

In [13]:
num.random.randint(1,8,(2,3))   ## 1 8 arasında 2 ye 3 lük rastgele arrray oluşturur

array([[1, 6, 5],
       [5, 3, 3]])

In [10]:
num.random.normal(1,8, 10) ## ort 1 standart sap. 8 olan 10 sayı

array([  9.12425039,  -0.49116825,  12.29998788, -10.03524041,
        -5.18825214,   8.46391241,  15.46835209,   5.73236786,
        11.30632026,  -4.71950842])

In [11]:
a.ndim    ## aray boyutu

1

In [12]:
a.shape  ## boyut bilgisi

(6,)

In [13]:
a.size   ## eleman sayısı

6

In [14]:
a.dtype   ##tipi

dtype('int32')

In [15]:
num.arange(1,10).reshape((3,3))   ## boyut kazandırır

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
x=num.array([1,2,4,5,6])
y=num.array([1,2,4,5,6])

In [17]:
num.concatenate([x,y])    ## array birleştirir

array([1, 2, 4, 5, 6, 1, 2, 4, 5, 6])

In [18]:
f=num.array([1,2,3,5,6,8,8,6,54,2,3])

In [19]:
num.split(f,[2,5])   ## 2. ile 5 e kadar olanı ayırır

[array([1, 2]), array([3, 5, 6]), array([ 8,  8,  6, 54,  2,  3])]

In [ ]:
x,y,z=num.split(f,[2,5])    ## x y z ye atar

In [ ]:
x

In [ ]:
y

In [ ]:
m=num.arange(16).reshape(4,4)

In [ ]:
m

In [20]:
f=num.array([1,2,3,5,6,8,8,6,54,2,3])

In [21]:
num.sort(f)            ## sıralar

array([ 1,  2,  2,  3,  3,  5,  6,  6,  8,  8, 54])

In [22]:
f.sort       ## yapısını değiştirir

<function ndarray.sort>

In [23]:
y=num.random.normal(5,3,(3,3))
y

array([[ 4.0228302 ,  3.46781555, -5.83018773],
       [ 1.0527011 ,  7.26548118,  6.06488014],
       [ 4.78592861,  9.17701524,  3.56326961]])

In [ ]:
num.sort(y, axis=1)    ## satırı kendi içinde sıralar

In [24]:
t= num.random.normal(5,3,(3,3))
t

array([[6.32931468, 6.16426564, 3.25320293],
       [8.06021363, 1.30474028, 1.58923905],
       [2.51082607, 4.71179964, 7.27541119]])

In [26]:
num.sort(t, axis= 0)

array([[2.51082607, 1.30474028, 1.58923905],
       [6.32931468, 4.71179964, 3.25320293],
       [8.06021363, 6.16426564, 7.27541119]])

In [ ]:
num.sort(y, axis=0)    ## sütuna göre sıralar

In [27]:
y[1,1]    ## indexe erişir

7.2654811777835135

In [28]:
y[1,1]=0.1111111

In [29]:
y

array([[ 4.0228302 ,  3.46781555, -5.83018773],
       [ 1.0527011 ,  0.1111111 ,  6.06488014],
       [ 4.78592861,  9.17701524,  3.56326961]])

In [34]:
a=num.arange(3,15)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
a[2:10:2]   ## 2. indexten başla 2 şer git

array([ 5,  7,  9, 11])

In [40]:
b=num.random.randint(20, size=(3,3))
b

array([[ 2, 17,  4],
       [18, 19,  5],
       [ 0,  3,  2]])

In [41]:
b[:,0]     ## bütün satırları seç 0. sütunu al

array([ 2, 18,  0])

In [42]:
b[:,1] 

array([17, 19,  3])

In [43]:
b[0,:]     ## 0. satırı seç

array([ 2, 17,  4])

In [47]:
b[: , 0:2]   # 0 dan 1 e kadar satırları 0 dan 1 e kadar sütunları al

array([[ 2, 17],
       [18, 19],
       [ 0,  3]])

In [48]:
m=num.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
altküm= m[0:2,1:3]
altküm

array([[1, 2],
       [5, 6]])

In [50]:
altküm[1,1]=3333

In [51]:
altküm

array([[   1,    2],
       [   5, 3333]])

In [52]:
m      ##yeni bir atama hem alt kümeyi hem diziyi değiştirdi

array([[   0,    1,    2,    3],
       [   4,    5, 3333,    7],
       [   8,    9,   10,   11],
       [  12,   13,   14,   15]])

In [53]:
altküm= m[0:2,1:3].copy()   ## copy ile sadece alt küme değişir ana array değişmez
altküm

array([[   1,    2],
       [   5, 3333]])

In [54]:
altküm[1,1]=2222
altküm

array([[   1,    2],
       [   5, 2222]])

In [55]:
m

array([[   0,    1,    2,    3],
       [   4,    5, 3333,    7],
       [   8,    9,   10,   11],
       [  12,   13,   14,   15]])

In [56]:
p=num.arange(2,16)
p

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
al=[2,5,7]

In [58]:
p[al]            ##fancy yani içinde o indexleri çeker alır

array([4, 7, 9])

In [59]:
p=num.arange(16).reshape(4,4)
p


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
p[1,[2,3]]    ## 1. satır 2 ve 3. sütun

array([6, 7])

In [61]:
p[1: ,[2,3]]    ## slice yani 1 den başla sonrakileri al

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [62]:
p=num.arange(2,16)
p

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [63]:
p<6    ## koşul

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False])

In [64]:
p[p<6]    ## true değerler geldi

array([2, 3, 4, 5])

In [65]:
p[p==6]

array([6])

In [66]:
p[p!=3]

array([ 2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [67]:
p*2

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [68]:
p**2

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196,
       225], dtype=int32)

In [69]:
 num.add(p,2)     ## bütün elemanlara 2 eklesin

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [70]:
 num.subtract(p,7)  ## 7 çıkar

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [71]:
num.divide(p,4)   ## 4 e böl

array([0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ,
       3.25, 3.5 , 3.75])

In [72]:
num.mod(p,2)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [73]:
num.cos(180)

-0.5984600690578581

In [74]:
n=num.array([3,5,100])

In [75]:
num.log10(n)

array([0.47712125, 0.69897   , 2.        ])

In [76]:
a=num.array([[3,5] ,[1,2]])   ### 3x+5y=8 ve x+2y=4 çözümü
b=num.array([8,4])

In [77]:
x=num.linalg.solve(a,b)
x

array([-4.,  4.])

In [78]:
 ********************************* PANDAS *******************************************************

SyntaxError: invalid syntax (<ipython-input-78-7eb060ff159e>, line 1)

In [2]:
import pandas as pd

In [85]:
a= pd.Series([1,20,4,44,352,7,1,2,4,845,35,7,1,2,4,445,35,7,1,2,4,245,35,7,1,2,4,625,35,7])
a


0       1
1      20
2       4
3      44
4     352
5       7
6       1
7       2
8       4
9     845
10     35
11      7
12      1
13      2
14      4
15    445
16     35
17      7
18      1
19      2
20      4
21    245
22     35
23      7
24      1
25      2
26      4
27    625
28     35
29      7
dtype: int64

In [86]:
a.axes

[RangeIndex(start=0, stop=30, step=1)]

In [87]:
a.size

30

In [88]:
a.values

array([  1,  20,   4,  44, 352,   7,   1,   2,   4, 845,  35,   7,   1,
         2,   4, 445,  35,   7,   1,   2,   4, 245,  35,   7,   1,   2,
         4, 625,  35,   7], dtype=int64)

In [89]:
a.head()   ## ilk 5 gözlem

0      1
1     20
2      4
3     44
4    352
dtype: int64

In [90]:
a.head(3)

0     1
1    20
2     4
dtype: int64

In [95]:
a.tail(2)

e    35
f     7
dtype: int64

In [91]:
a= pd.Series([1,2,4,445,35,7], index=[3,5,7,9,3,1])     ##indexi sen belirlersin
a

3      1
5      2
7      4
9    445
3     35
1      7
dtype: int64

In [92]:
a= pd.Series([1,2,4,445,35,7], index=["a","b","c","d","e","f"])
a

a      1
b      2
c      4
d    445
e     35
f      7
dtype: int64

In [96]:
a["c"]

4

In [97]:
a["a":"c"]

a    1
b    2
c    4
dtype: int64

In [100]:
s=pd.Series(["c1",1,2,3,4,6,8,76,2,3,4,6,8,5,5,35,64])
n=pd.Series(["c2",1,2,3,4,6,8,76,8,76,89,25,64,24,75])

In [101]:
pd.concat([s,n])       ## birleştirir

0     c1
1      1
2      2
3      3
4      4
5      6
6      8
7     76
8      2
9      3
10     4
11     6
12     8
13     5
14     5
15    35
16    64
0     c2
1      1
2      2
3      3
4      4
5      6
6      8
7     76
8      8
9     76
10    89
11    25
12    64
13    24
14    75
dtype: object

In [106]:
s.keys

<bound method Series.keys of 0     c1
1      1
2      2
3      3
4      4
5      6
6      8
7     76
8      2
9      3
10     4
11     6
12     8
13     5
14     5
15    35
16    64
dtype: object>

In [102]:
5 in s

True

In [103]:
9 in n

True

In [107]:
345 in s

False

In [108]:
pd.DataFrame(s, columns=["Sayılar"])

Sayılar
0       c1
1        1
2        2
3        3
4        4
5        6
6        8
7       76
8        2
9        3
10       4
11       6
12       8
13       5
14       5
15      35
16      64

In [110]:
m=num.arange(0,9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [111]:
pf= pd.DataFrame(m, columns=["1","2","3"])
pf

1  2  3
0  0  1  2
1  3  4  5
2  6  7  8

In [113]:
pf.index=("a","bb","c")
pf

1  2  3
a   0  1  2
bb  3  4  5
c   6  7  8

In [114]:
pf.drop("a",axis=0)      ## a yok 

1  2  3
bb  3  4  5
c   6  7  8

In [115]:
pf         ## kalıcı değil

1  2  3
a   0  1  2
bb  3  4  5
c   6  7  8

In [116]:
pf.drop("a",axis=0 , inplace=True)    ## inplace kalıcı halde kaldırır

In [117]:
pf

1  2  3
bb  3  4  5
c   6  7  8

In [118]:
pf["1"]                  ## axis=0 satır    axis=1 sütun

bb    3
c     6
Name: 1, dtype: int32

In [119]:
pf.drop("1", axis=1)        ## 1 adlı sütunu sil

2  3
bb  4  5
c   7  8

In [128]:
rt =num.random.randint(1,8,(3,3)) 


array([[2, 3, 5],
       [5, 4, 6],
       [1, 2, 5]])

In [131]:
a =  pd.DataFrame(rt, columns=["a","b","c"])
a

a  b  c
0  2  3  5
1  5  4  6
2  1  2  5

In [ ]:
h= num.arange(0,25).reshape(5,5)
h

In [127]:
a = pd.DataFrame(rt, columns=["a"])
a

a
0  88
1   1
2  24
3  75

In [133]:
a["x"] = a["a"] * a["b"]       #ikisini çarpar yeri kolon ekler
a

a  b  c   x
0  2  3  5   6
1  5  4  6  20
2  1  2  5   2

In [142]:
ilk= pd.DataFrame(a, columns=["a","b","c"])
ilk


a  b  c
0  2  3  5
1  5  4  6
2  1  2  5

In [155]:
l=["a"]   # a sütünü sildi

In [156]:
ilk.drop(l,axis=1)

b  c
0  3  5
1  4  6
2  2  5

In [149]:
g=num.random.randint(1,20, size=[5,4])
g

array([[ 8, 10, 16,  2],
       [ 8, 17, 19, 11],
       [18,  3,  2, 10],
       [18, 13,  7, 15],
       [18, 19, 14, 16]])

In [151]:
a= pd.DataFrame(g , columns=["a","x","y","z"])
a

a   x   y   z
0   8  10  16   2
1   8  17  19  11
2  18   3   2  10
3  18  13   7  15
4  18  19  14  16

In [157]:
a.loc[0:3]           ## 3 dahil

a   x   y   z
0   8  10  16   2
1   8  17  19  11
2  18   3   2  10
3  18  13   7  15

In [158]:
a.iloc[0:3]       ## 3 dahil değil

a   x   y   z
0   8  10  16   2
1   8  17  19  11
2  18   3   2  10

In [162]:
a.loc[0:3, "x"]        ## index seçiminde loc kullan iloc hata verir

0    10
1    17
2     3
3    13
Name: x, dtype: int32

In [161]:
a.iloc[0:3] ["x"]   

0    10
1    17
2     3
Name: x, dtype: int32

In [164]:
a.x

0    10
1    17
2     3
3    13
4    19
Name: x, dtype: int32

In [166]:
a[a.x>10]     ## cs 10 dan büyük olanları alır

a   x   y   z
1   8  17  19  11
3  18  13   7  15
4  18  19  14  16

In [172]:
a[(a.y>10) & (a.x < 20)][["x","y"]]  ## şartları sağlayan x ve y yi seçer

x   y
0  10  16
1  17  19
4  19  14

In [169]:
t=num.arange(16).reshape(4,4)
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [170]:

x=pd.DataFrame(t , columns=["1","2","3","4"])
x

1   2   3   4
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [171]:
y=x+100            ## her elemanına 100 ekler
y

1    2    3    4
0  100  101  102  103
1  104  105  106  107
2  108  109  110  111
3  112  113  114  115

In [173]:
 pd.concat([x,y] , ignore_index=True)##index problemi kalkar         ##birleştirir

1    2    3    4
0    0    1    2    3
1    4    5    6    7
2    8    9   10   11
3   12   13   14   15
4  100  101  102  103
5  104  105  106  107
6  108  109  110  111
7  112  113  114  115

In [3]:
a= pd.DataFrame({"Takımlar": ["FB","GS","BJK","TS"],"YIL": [1907,1905,1903,1961]})
a

Takımlar   YIL
0       FB  1907
1       GS  1905
2      BJK  1903
3       TS  1961

In [6]:
b= pd.DataFrame({"Takımlar": ["FB","GS","BJK","TS"],"RENK": ["Sarı","Kırmızı","Beyaz","Bordo"]})
b

Takımlar     RENK
0       FB     Sarı
1       GS  Kırmızı
2      BJK    Beyaz
3       TS    Bordo

In [7]:
pd.merge(a,b)   #birleştirme işlemi yapar

Takımlar   YIL     RENK
0       FB  1907     Sarı
1       GS  1905  Kırmızı
2      BJK  1903    Beyaz
3       TS  1961    Bordo

In [175]:
a["YIL"].min()

1903

In [176]:
a["YIL"].count()

4

In [177]:
a["YIL"].sum()

7676

In [180]:
a.describe()  ##T Transpoze

YIL
count     4.000000
mean   1919.000000
std      28.047579
min    1903.000000
25%    1904.500000
50%    1906.000000
75%    1920.500000
max    1961.000000

In [ ]:
a["YIL"].mean()    ##ortalama

In [8]:
import seaborn as sns

In [10]:
df = sns.load_dataset("planets")


In [11]:
df.shape

(1035, 6)

In [13]:
df.mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [14]:
df["mass"].mean()

2.6381605847953233

In [15]:
df["mass"].min()

0.0036

In [21]:
b=pd.DataFrame({"c1": [35,51,25,85,35,35,51,25,85,35,35,51,25,85,35,35,51,25,85,35,35,51,25,85,35,35,51,25,85,35] , 
                "c2": [34,75,87,90,54,78,23,66,85,25,34,75,87,90,54,78,23,66,85,25,34,75,87,90,54,78,23,66,85,25]} )
b

c1  c2
0   35  34
1   51  75
2   25  87
3   85  90
4   35  54
5   35  78
6   51  23
7   25  66
8   85  85
9   35  25
10  35  34
11  51  75
12  25  87
13  85  90
14  35  54
15  35  78
16  51  23
17  25  66
18  85  85
19  35  25
20  35  34
21  51  75
22  25  87
23  85  90
24  35  54
25  35  78
26  51  23
27  25  66
28  85  85
29  35  25

In [20]:
df.dropna().describe().T   ##eksik değerleri siler

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

In [23]:
b.groupby("c1")          ##gruplandırır

In [24]:
b.groupby("c1").mean()     ##ortalamalarını aldı

c2
c1       
25  76.50
35  47.75
51  49.00
85  87.50

In [25]:
b.groupby("c1").sum()  

c2
c1     
25  459
35  573
51  294
85  525

In [16]:
df["mass"].var()

14.58183312700122

In [18]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [35]:
df.groupby("method").max()

number  orbital_period   mass  distance  year
method                                                                      
Astrometry                          1     1016.000000    NaN     20.77  2013
Eclipse Timing Variations           2    10220.000000   6.05    500.00  2012
Imaging                             4   730000.000000    NaN    165.00  2013
Microlensing                        2     5100.000000    NaN   7720.00  2013
Orbital Brightness Modulation       2        1.544929    NaN   1180.00  2013
Pulsar Timing                       3    36525.000000    NaN   1200.00  2011
Pulsation Timing Variations         1     1170.000000    NaN       NaN  2007
Radial Velocity                     6    17337.500000  25.00    354.00  2014
Transit                             7      331.600590   1.47   8500.00  2014
Transit Timing Variations           3      160.000000    NaN   2119.00  2014

In [38]:
df.groupby("method")["distance"].describe()

count         mean          std      min  \
method                                                                    
Astrometry                       2.0    17.875000     4.094148    14.98   
Eclipse Timing Variations        4.0   315.360000   213.203907   130.72   
Imaging                         32.0    67.715937    53.736817     7.69   
Microlensing                    10.0  4144.000000  2076.611556  1760.00   
Orbital Brightness Modulation    2.0  1180.000000     0.000000  1180.00   
Pulsar Timing                    1.0  1200.000000          NaN  1200.00   
Pulsation Timing Variations      0.0          NaN          NaN      NaN   
Radial Velocity                530.0    51.600208    45.559381     1.35   
Transit                        224.0   599.298080   913.876990    38.00   
Transit Timing Variations        3.0  1104.333333   915.819487   339.00   

                                     25%       50%        75%      max  
method                                                                  
Astrometry                       16.4275    17.875    19.3225    20.77  
Eclipse Timing Variations       130.7200   315.360   500.0000   500.00  
Imaging                          22.1450    40.395   132.6975   165.00  
Microlensing                   2627.5000  3840.000  4747.5000  7720.00  
Orbital Brightness Modulation  1180.0000  1180.000  1180.0000  1180.00  
Pulsar Timing                  1200.0000  1200.000  1200.0000  1200.00  
Pulsation Timing Variations          NaN       NaN        NaN      NaN  
Radial Velocity                  24.4125    40.445    59.2175   354.00  
Transit                         200.0000   341.000   650.0000  8500.00  
Transit Timing Variations       597.0000   855.000  1487.0000  2119.00

In [27]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [42]:
df.groupby("number").aggregate(["min",num.median,"max"])    ## görmek istediğin özellikleri bu şekilde görebilirsin

orbital_period                             mass                  \
                  min    median           max      min  median     max   
number                                                                   
1            0.090706  66.26200  730000.00000  0.00360  1.7900  25.000   
2            0.240104  42.63180    9017.80000  0.00870  0.9900  21.420   
3            0.453285  33.94100   14002.00000  0.00755  0.0580   8.060   
4            1.937780  43.37030  170000.00000  0.00600  0.6876   4.132   
5            0.736540  13.91331    4909.00000  0.16500  0.4860   3.530   
6            4.312300  36.82300    2248.00000  0.00800  0.0194   0.205   
7            7.008151  91.93913     331.60059      NaN     NaN     NaN   

       distance                    year               
            min   median      max   min median   max  
number                                                
1          1.35   77.820  8500.00  1989   2009  2014  
2          8.82   46.340  4080.00  1998   2011  2014  
3          6.06   30.075  1400.00  1992   2011  2014  
4          4.70   13.470    39.94  1996   2008  2014  
5         12.53  296.500   368.00  1996   2011  2014  
6          6.80   26.110   613.00  2008   2010  2013  
7        780.00  780.000   780.00  2013   2013  2013

In [45]:
df.groupby("method").aggregate({"year": "max", "distance": "max"}) 

year  distance
method                                       
Astrometry                     2013     20.77
Eclipse Timing Variations      2012    500.00
Imaging                        2013    165.00
Microlensing                   2013   7720.00
Orbital Brightness Modulation  2013   1180.00
Pulsar Timing                  2011   1200.00
Pulsation Timing Variations    2007       NaN
Radial Velocity                2014    354.00
Transit                        2014   8500.00
Transit Timing Variations      2014   2119.00

In [65]:
b.groupby("c1")

In [74]:
def fonks(b):
    return b["c1"].std()>0


In [75]:
b.groupby("c1").filter(fonks)

Empty DataFrame
Columns: [c1, c2]
Index: []

In [ ]:
b["not"]*3

In [76]:
x=pd.DataFrame({"first": [1,2,3,4,5,6,7,1,2,3,4,5,6,7] ,
                "second":[11,22,33,44,55,66,77,3,5,64,3,1,67,86], 
                "third": [12,3,57,65,25,76,91,12,45,74,23,65,43,12]} ,columns=["first","second","third"])
x

first  second  third
0       1      11     12
1       2      22      3
2       3      33     57
3       4      44     65
4       5      55     25
5       6      66     76
6       7      77     91
7       1       3     12
8       2       5     45
9       3      64     74
10      4       3     23
11      5       1     65
12      6      67     43
13      7      86     12

In [77]:
x.groupby("first")

In [78]:
x.groupby("first",).sum()

second  third
first               
1          14     24
2          27     48
3          97    131
4          47     88
5          56     90
6         133    119
7         163    103

In [79]:
x["second"]*6

0      66
1     132
2     198
3     264
4     330
5     396
6     462
7      18
8      30
9     384
10     18
11      6
12    402
13    516
Name: second, dtype: int64

In [80]:
pd.DataFrame(x)


first  second  third
0       1      11     12
1       2      22      3
2       3      33     57
3       4      44     65
4       5      55     25
5       6      66     76
6       7      77     91
7       1       3     12
8       2       5     45
9       3      64     74
10      4       3     23
11      5       1     65
12      6      67     43
13      7      86     12

In [81]:
b=x.iloc[:,:2]
b

first  second
0       1      11
1       2      22
2       3      33
3       4      44
4       5      55
5       6      66
6       7      77
7       1       3
8       2       5
9       3      64
10      4       3
11      5       1
12      6      67
13      7      86

In [82]:
b.transform(lambda x:x-x.mean() )          ##sayıdan aritmetik ort çıkarıp yazdı

first     second
0    -3.0 -27.357143
1    -2.0 -16.357143
2    -1.0  -5.357143
3     0.0   5.642857
4     1.0  16.642857
5     2.0  27.642857
6     3.0  38.642857
7    -3.0 -35.357143
8    -2.0 -33.357143
9    -1.0  25.642857
10    0.0 -35.357143
11    1.0 -37.357143
12    2.0  28.642857
13    3.0  47.642857

In [83]:
x.apply(num.sum)    ## satır toplamlarını yazdı

first      56
second    537
third     603
dtype: int64

In [84]:
x.groupby("first").apply(num.sum)   ##grupları kendi içinde birştirip topadı

first  second  third
first                      
1          2      14     24
2          4      27     48
3          6      97    131
4          8      47     88
5         10      56     90
6         12     133    119
7         14     163    103

In [86]:
x["first"].max() + x["second"].min()

7

In [87]:
import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic.head(6)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True

In [104]:
titanic.groupby(["class","sex"])["survived"].aggregate("mean").unstack() 


sex       female      male
class                     
First   0.968085  0.368852
Second  0.921053  0.157407
Third   0.500000  0.135447

In [105]:
titanic.groupby("class")["survived"].mean()


class
First     0.629630
Second    0.472826
Third     0.242363
Name: survived, dtype: float64

In [144]:
t= pd.read_csv("turkey_car_market.csv",sep=",")
t

İlan Tarihi    Marka Arac Tip Grubu             Arac Tip  Model Yıl  \
0     27/05/2020   Jaguar             XF  2.0 D Prestige Plus     2017.0   
1     16/06/2020    Acura             CL                    -     2015.0   
2     14/06/2020    Acura             CL                  2.2     1994.0   
3     11/06/2020    Acura             CL                    -     2013.0   
4     11/06/2020    Acura             CL                  2.2     2010.0   
5     04/06/2020    Acura             CL                  2.2     1999.0   
6     03/06/2020    Acura             CL                  2.2     2014.0   
7     02/06/2020    Acura             CL                    -     2014.0   
8     29/05/2020    Acura            RSX               Type-S     2019.0   
9     29/05/2020    Acura            RSX               Type-S     2019.0   
10    24/05/2020    Acura             CL                    -     2001.0   
11    08/05/2020    Acura             CL                    -     2010.0   
12    07/05/2020    Acura             CL                    -     2014.0   
13    27/04/2020    Acura             CL                    -     2004.0   
14    27/04/2020    Acura             CL                    -     2004.0   
15    24/04/2020    Acura             CL                    -     2012.0   
16    23/04/2020    Acura             CL                    -     2017.0   
17    23/04/2020    Acura             CL                    -     2013.0   
18    21/04/2020    Acura             CL                    -     2004.0   
19    08/04/2020     Jeep       Wrangler              2.8 CRD     2014.0   
20    20/04/2020    Acura            RSX               Type-S     2019.0   
21    20/04/2020    Acura            RSX               Type-S     2019.0   
22    20/04/2020    Acura             CL                  2.2     2012.0   
23    20/04/2020    Acura            RSX               Type-S     2019.0   
24    15/04/2020    Acura            RSX               Type-S     2019.0   
25    15/04/2020    Acura            RSX               Type-S     2019.0   
26    15/04/2020    Acura             CL                    -     2009.0   
27    15/04/2020    Acura             CL                    -     2009.0   
28    14/04/2020    Acura             CL                  2.2     2016.0   
29    14/04/2020    Acura             CL                    -     2011.0   
...          ...      ...            ...                  ...        ...   
9014  13/06/2020    Tofaş          Doğan                   SL     1993.0   
9015  13/06/2020    Tofaş          Doğan                    S     1994.0   
9016  13/06/2020    Tofaş          Şahin        Şahin 5 vites     1992.0   
9017  13/06/2020    Tofaş          Serçe                Serçe     1990.0   
9018  13/06/2020    Tofaş          Şahin                  1.6     1996.0   
9019  13/06/2020    Tofaş          Şahin                  1.6     1995.0   
9020  12/06/2020    Tofaş          Şahin                  1.6     1996.0   
9021  12/06/2020    Tofaş          Şahin        Şahin 5 vites     1992.0   
9022  12/06/2020    Tofaş          Doğan                  SLX     1993.0   
9023  12/06/2020    Tofaş          Doğan                    L     1991.0   
9024  11/06/2020    Tofaş          Şahin        Şahin 5 vites     1994.0   
9025  11/06/2020    Tofaş          Şahin        Şahin 5 vites     1994.0   
9026  11/06/2020    Tofaş          Şahin                  1.4     1999.0   
9027  11/06/2020    Tofaş         Kartal               1.6 ie     2001.0   
9028  11/06/2020    Tofaş          Şahin                  1.6     1994.0   
9029  11/06/2020    Tofaş          Şahin                    S     1996.0   
9030  11/06/2020    Tofaş          Doğan                  1.6     1985.0   
9031  11/06/2020    Tofaş          Doğan                    L     1992.0   
9032  09/06/2020    Tofaş          Doğan                    L     1990.0   
9033  03/06/2020  Hyundai            I20             1.2 Team     2011.0   
9034  09/06/2020    Tofaş          Doğan             

In [146]:
t.dropna().describe().T 

count           mean            std     min      25%       50%  \
Model Yıl  9044.0    2011.824082       6.609711  1959.0   2010.0    2014.0   
Km         9044.0  135812.800862   93421.522813     0.0  68000.0  125000.0   
Fiyat      9044.0  148069.638655  221977.857167  5500.0  60937.5   95500.0   

                75%        max  
Model Yıl    2017.0     2020.0  
Km         194130.0  1850000.0  
Fiyat      153562.5  5086500.0

In [118]:
t.groupby("Car_Name")["Selling_Price"].mean()

Car_Name
800                          0.350000
Activa 3g                    0.310000
Activa 4g                    0.400000
Bajaj  ct 100                0.180000
Bajaj Avenger 150            0.750000
Bajaj Avenger 150 street     0.600000
Bajaj Avenger 220            0.790000
Bajaj Avenger 220 dtsi       0.525000
Bajaj Avenger Street 220     0.450000
Bajaj Discover 100           0.270000
Bajaj Discover 125           0.175000
Bajaj Dominar 400            1.450000
Bajaj Pulsar  NS 200         0.600000
Bajaj Pulsar 135 LS          0.400000
Bajaj Pulsar 150             0.300000
Bajaj Pulsar 220 F           0.515000
Bajaj Pulsar NS 200          0.483333
Bajaj Pulsar RS200           1.050000
Hero  CBZ Xtreme             0.200000
Hero  Ignitor Disc           0.200000
Hero Extreme                 0.600000
Hero Glamour                 0.250000
Hero Honda CBZ extreme       0.380000
Hero Honda Passion Pro       0.300000
Hero Hunk                    0.200000
Hero Passion Pro             0.425000
Her

In [109]:
pd.read_csv("duz_metin.txt",sep=";")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [111]:
pd.read_excel("ornekx.xlsx")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0